### PR TITLE
Upgrade Elixir to fix Travis CI

### PR DESCRIPTION
**Pull request by tcyrus**
Use releases of Elixir that implement [`Kernel.ceil`](https://hexdocs.pm/elixir/Kernel.html#ceil/1)

### CODE REVIEW

**Comment by tcyrus** [comment]
@likeanocean Sorry for pinging you, but is there anything holding this back?

**Comment by likeanocean** [comment]
Hi Timothy!

There is not. It's fallen through because we haven't had anyone responsible for this repository :(

Just two suggestions:

- Please include Elixir 1.7 in the list of language versions. I think we'd like to continue supporting that.
- Please add a trailing new line to the end of this file!

Otherwise, this PR looks great. Thank you for your help! <3

**Comment by tcyrus** [comment]
@likeanocean Done

**Comment by tcyrus** [comment]
That seems to have fixed it

**Comment by likeanocean** [comment]
Yup, fixed. Thank you! :D

**Pull request merged**
